### ISSUE TITLE
How to make user admin 

### ISSUE THREAD

**Issue by JustinWrld** [FinGu/c_auth#10]
how do I make a user admin, Please and Thanks you

**Comment by JustinWrld** [comment]
and im having a error with c# example i changed the website and put all the application keys etc in and it gives me this
![1unknown](https://user-images.githubusercontent.com/67561267/117563173-1fba5e80-b072-11eb-97a4-ad9f6b4ca84f.png)

**Comment by FinGu** [comment]
> how do I make a user admin, Please and Thanks you

github issue trackers aren't for support

> and im having a error with c# example i changed the website and put all the application keys etc in and it gives me this
> ![1unknown](https://user-images.githubusercontent.com/67561267/117563173-1fba5e80-b072-11eb-97a4-ad9f6b4ca84f.png)

send the file with the exception details

**Comment by JustinWrld** [comment]
Details :
```
System.FormatException
  HResult=0x80131537
  Message=Could not find any recognizable digits.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ParseNumbers.StringToInt(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)
   at System.Convert.ToByte(String value, Int32 fromBase)
   at c_auth.encryption.str_to_byte_arr(String hex) in C:\Users\justi\Downloads\c#cauth example\examples\net_core\c_auth.cs:line 367
   at c_auth.encryption.decrypt_string(String cipher_text, Byte[] key, Byte[] iv) in C:\Users\justi\Downloads\c#cauth example\examples\net_core\c_auth.cs:line 405
   at c_auth.encryption.decrypt(String message, String enc_key, String iv) in C:\Users\justi\Downloads\c#cauth example\examples\net_core\c_auth.cs:line 438
   at c_auth.api.init() in C:\Users\justi\Downloads\c#cauth example\examples\net_core\c_auth.cs:line 89
   at c_auth.Program.Main(String[] args) in C:\Users\justi\Downloads\c#cauth example\examples\net_core\Program.cs:line 23
```

your c# example with the things changed to my website for my hosting I use infinity free not sure if it could be the reason.
[net_framework.zip](https://github.com/FinGu/c_auth/files/6449065/net_framework.zip)

**Comment by FinGu** [comment]
https://support.infinityfree.net/websites/javascript-error-using-api-or-mobile-android-app/
